// Generated by CoffeeScript 1.7.1
(function() {
  var respond, restify, server;

  restify = require('restify');

  respond = function(request, response, next) {
    response.send('Hello ' + request.params.name);
    return next();
  };

  server = restify.createServer();

  server.get('/hello/:name', function(request, response, next) {
    return response.send(201);
  });

  server.listen(9005, function() {
    return console.log('%s is listening at %', server.name, server.url);
  });

}).call(this);


//# sourceMappingURL=server.map
